// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDVZ01U0pvxoYGNUwdwY_18uG7RY8UokU',
    appId: '1:552492159103:web:fcf216a75f28321c75af4a',
    messagingSenderId: '552492159103',
    projectId: 'macroquant-4f43d',
    authDomain: 'macroquant-4f43d.firebaseapp.com',
    storageBucket: 'macroquant-4f43d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmX9HTNimtue6ovrCmEgDjfSuRIkHdX0',
    appId: '1:552492159103:android:503002ee1a11003575af4a',
    messagingSenderId: '552492159103',
    projectId: 'macroquant-4f43d',
    storageBucket: 'macroquant-4f43d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_y1cejBJ5pJHM4yCgzIeBzoA92n97R4w',
    appId: '1:552492159103:ios:551e9690c9729edc75af4a',
    messagingSenderId: '552492159103',
    projectId: 'macroquant-4f43d',
    storageBucket: 'macroquant-4f43d.firebasestorage.app',
    iosClientId: '552492159103-f63np95vmn99p3ejo0n64guavvc1k94q.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
