/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AppApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BINANCE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BINANCE_API_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FIREBASE_SERVICE_ACCOUNT_B64": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramWebhook": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}

import "sst"
export {}